# Generated by Django 4.2.18 on 2025-01-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherquery',
            old_name='temp',
            new_name='temperature',
        ),
        migrations.AddField(
            model_name='weatherquery',
            name='icon',
            field=models.URLField(blank=True, null=True),
        ),
    ]
